---
title: "class notes"
format: html
editor: visual
---

# Notes

error catching function / control flow

```{r}
x=6
y=4

if (x%%2==1 & y%%2 == 0)
{stop("x odd y even")
} else if (x > 3 && y <= 3) {
  print('Hello World')
} else if (x > 3) {
  print("!dlrow olleH")
} else if (x <= 3) {
  print('something else...')
} 


```

```{r}
# a = rbeta(100,0.50, 0.5)
a = rnorm(5,0,1)
a
```

```{r}
a = c(a)
typeof(a)
```

# Loops

```{r}
# can use with atomic or generic vectors 
seq_along(NA)
```

# 9/14 Lecture 

```{r}
(df = data.frame(
  x = 1:3, 
  y = c("a", "b", "c"),
  z = c(TRUE)
))
```

```{r}
attributes(df)
```

```{r}
str(df) # df is just a list 
```

What is this text block?

```{=tex}
\sum_{i=1}^{n}
```
$$
\sum_{i=1}^n
$$

```{r}
y = list(1,4,7,12)
y[1]
```

```{r}
# single brackets are subsetting 
# double is extracting 
y[[2]]
```

```{r}
typeof(c(1,2))
typeof(c(1L,2L))
```

## Exercise 1 

```{r}
x = c(56, 3, 17, 2, 4, 9, 6, 5, 19, 5, 2, 3, 5, 0, 13, 12, 6, 31, 10, 21, 8, 4, 1, 1, 2, 5, 16, 1, 3, 8, 1,
      3, 4, 8, 5, 2, 8, 6, 18, 40, 10, 20, 1, 27, 2, 11, 14, 5, 7, 0, 3, 0, 7, 0, 8, 10, 10, 12, 8, 82,
      21, 3, 34, 55, 18, 2, 9, 29, 1, 4, 7, 14, 7, 1, 2, 7, 4, 74, 5, 0, 3, 13, 2, 8, 1, 6, 13, 7, 1, 10,
      5, 2, 4, 4, 14, 15, 4, 17, 1, 9)
```

-   Select every third value starting at position 2 in `x`.

-   Remove all values with an odd index (e.g. 1, 3, etc.)

-   Remove every 4th value, but only if it is odd.

```{r}
a = seq(2,100,by=3)
x[a]
```

```{r}
not_a = seq(1,100,by=2)
x[-not_a]
```

```{r}
odd_4 = seq(0,100,by=4)
x[x[odd_4] %% 2 == 0]
```

```{python}
x = [1,3,3]
[i for i in range(1,100,3)]
```
